### ISSUE TITLE
Particle ids passed into SCS constructor.

### ISSUE THREAD

**Issue by diamog** [SCOREC/particle_structures#10]
The SCS takes an array of vectors of [particle ids](url) which is then never used besides in an assertion. As far as I can tell it was only ever used for debugging purposes. I'm guessing I had a reason for adding them, but I do not see it now. @cwsmith do you recall or see a usage for these ids?

For the time being, I've taken the argument out of the device default version and if we don't see a need for it, then it will be removed with the merge.

**Comment by cwsmith** [comment]
Removing the particle id arg should be fine.  I think it was added for debugging/visualization.
