### ISSUE TITLE
Macros with commas

### ISSUE THREAD

**Issue by diamog** [SCOREC/particle_structures#5]
We are able to simply pass the code as an argument into the macros, but with one problem. The code cannot have any unprotected commas (protected commas appear within a set of parentheses () brackets, [] and {}, do not count). So with our current Push algorithm, the following lines cannot be done as they are currently inside the macro: 

https://github.com/SCOREC/particle_structures/blob/master/algorithms/Push.cpp#L345-L350

**Comment by cwsmith** [comment]
Closing this issue as we now have a functor/lambda based procedure to abstract these loops:

https://github.com/SCOREC/particle_structures/blob/26fa28dc72dc4a24e607726a00244fcf05d34ba3/test/lambdaTest.cpp#L33-L38
