### ISSUE TITLE
new_element indexing space for SCS rebuild

### ISSUE THREAD

**Issue by diamog** [SCOREC/particle_structures#9]
I found a bug in rebuild with the indexing of row_to_element. While trying to fix it I realized that there isn't an explicit statement of whether the new_element (which stores the destination element of each particle when rebuilding) should store mesh element indices or scs row indices. I am curious which is being used in the pseudo push in pumi_pic. I'm guessing it is mesh element indices, but I couldn't figure it out from reading the code.

**Comment by cwsmith** [comment]
It looks like we assume that `e` provided by the `SCS_LAMBDA(int e, ...)` is the mesh element id (i.e., it is passed to omega_h functions) and not the scs row index.   `e` is used to set the particle's parent element id which is eventually passed into rebuild.

**Comment by diamog** [comment]
Closing issue as the bug is fixed and this is the approach that will be used going forward
